name: sync to docker vercel

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: apk update && apk add ruby && apk add mustache

      - name: Run Build Script
        run: sh ./build.sh

      - name: Push to Another Repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS_HEE }}
        with:
          source-directory: 'output'
          destination-github-username: kimdohee58
          destination-repository-name: biday-front-vercel
          user-email: ${{ secrets.EMAIL_HEE }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main

      - name: push docker-vercel
        run: echo "$DESTINATION_CLONED_DIRECTORY"
